<?php
require_once '../includes/auth.php';
require_once '../config/smtp.php';
requireLogin();

header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $tripId = $_POST['trip_id'];
    $email = $_POST['email'] ?: $_SESSION['user_email'];
    
    // Get trip data
    $stmt = $pdo->prepare("SELECT * FROM trips WHERE id = ?");
    $stmt->execute([$tripId]);
    $trip = $stmt->fetch();
    
    // Get expenses
    $stmt = $pdo->prepare("
        SELECT e.*, u.name as paid_by_name 
        FROM expenses e 
        JOIN users u ON e.paid_by = u.id 
        WHERE e.trip_id = ? 
        ORDER BY e.date DESC
    ");
    $stmt->execute([$tripId]);
    $expenses = $stmt->fetchAll();
    
    // Generate email body
    $total = array_sum(array_column($expenses, 'amount'));
    $currency = getCurrencySymbol($trip['currency']);
    
    $emailBody = "
    <h2>Trip Expense Report: " . htmlspecialchars($trip['name']) . "</h2>
    <p><strong>Trip Duration:</strong> " . $trip['start_date'] . " to " . $trip['end_date'] . "</p>
    <p><strong>Budget:</strong> {$currency}" . number_format($trip['budget'], 2) . "</p>
    <p><strong>Total Spent:</strong> {$currency}" . number_format($total, 2) . "</p>
    
    <h3>Expense Details:</h3>
    <table border='1' style='border-collapse: collapse; width: 100%;'>
        <tr style='background-color: #f2f2f2;'>
            <th>Date</th>
            <th>Category</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Paid By</th>
        </tr>";
    
    foreach ($expenses as $expense) {
        $emailBody .= "
        <tr>
            <td>" . $expense['date'] . "</td>
            <td>" . htmlspecialchars($expense['category']) . "</td>
            <td>" . htmlspecialchars($expense['description']) . "</td>
            <td>{$currency}" . number_format($expense['amount'], 2) . "</td>
            <td>" . htmlspecialchars($expense['paid_by_name']) . "</td>
        </tr>";
    }
    
    $emailBody .= "
    </table>
    <br>
    <p><em>Generated by Haerriz Trip Finance on " . date('Y-m-d H:i:s') . "</em></p>
    ";
    
    $subject = "Trip Expense Report: " . $trip['name'];
    
    if (sendEmail($email, $subject, $emailBody)) {
        echo json_encode(['success' => true, 'message' => 'Report sent successfully']);
    } else {
        echo json_encode(['success' => false, 'message' => 'Failed to send email']);
    }
} else {
    echo json_encode(['success' => false]);
}

function getCurrencySymbol($currency) {
    $symbols = [
        'USD' => '$', 'EUR' => '€', 'GBP' => '£', 'JPY' => '¥', 'AUD' => 'A$',
        'CAD' => 'C$', 'INR' => '₹', 'THB' => '฿', 'VND' => '₫'
    ];
    return $symbols[$currency] ?? $currency;
}
?>