name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Hostinger Deployment
      run: |
        curl -X POST https://webhooks.hostinger.com/deploy/690aca6bb4927669891374cbba8493fc
        echo "Deployment triggered to expenses.haerriz.com"